### ISSUE TITLE
set animation speed

### ISSUE THREAD

**Issue by RajaReddyiOS** [antonio081014/SPWaterWaveProgressIndicatorView#2]
how to set duration for animation

**Comment by antonio081014** [comment]
What do you mean "duration"?, like how long for the whole animation?

**Comment by RajaReddyiOS** [comment]
i mean to slow down animation
actually i got that
thx

**Comment by antonio081014** [comment]
Alright, I think frequency should help.

**Comment by RajaReddyiOS** [comment]
nope density..

**Comment by antonio081014** [comment]
Alright.
