### ISSUE TITLE
square view loading

### ISSUE THREAD

**Issue by fukemy** [antonio081014/SPWaterWaveProgressIndicatorView#3]
Hello. Thanks you for great library. I need to display loading view in square, not circle. Can you give some help to implement this

**Comment by antonio081014** [comment]
Checkout the following code:
https://github.com/antonio081014/SPWaterWaveProgressIndicatorView/blob/master/WaterWaveDemo_Swift/WaterWaveDemo_Swift/SPWaterProgressIndicatorView.swift#L72-L76

replace path init with [init(rect:)](https://developer.apple.com/documentation/uikit/uibezierpath/1624359-init)

**Comment by fukemy** [comment]
Thanks you very much. It's work

**Comment by fukemy** [comment]
I got other problem, that text layer does not appear. I dont know why after a lot of search in your code 
![screen shot 2018-01-02 at 13 33 55](https://user-images.githubusercontent.com/8202437/34476244-abf25940-efc1-11e7-818a-e856c6f7aca6.png)
I am using objective-C code

**Comment by antonio081014** [comment]
Things to check:
- If text layer has been added.
- If text layer has been brought to front. (Position of Z-axis.)
