### ISSUE TITLE
The height of the wave

### ISSUE THREAD

**Issue by meshileya** [antonio081014/SPWaterWaveProgressIndicatorView#5]
Hello @antonio081014 , using WaterAnimatorView(frame: view.bounds) still gives me half of my entire screen.

I am looking forward to making the wave fill up an entire view controller, could there be anything I am doing wrong pls.

NOTE: I have also tried to set both the bottom and top constraints, but still having the same issue.

**Comment by fukemy** [comment]
hi there, WaterAnimatorView always need to ensure that it's square, u can see this piece of code:
```
override var frame: CGRect {
        didSet {
            if frame.width != frame.height {
                let side = min(frame.width, frame.height)
                frame = CGRect.init(x: frame.origin.x, y: frame.origin.y, width: side, height: side)
            }
        }
    }
```
That mean if width != height, the WaterAnimatorView will resized to the min value of width/height.
So, i u want it fill all screen, u need set left and right constant to margin as view width = height

**Comment by antonio081014** [comment]
@fukemy is right. 
I just updated README file for the confusion.
Thanks for the help.
